<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles pages, but only exists for the sake of child theme forward compatibility.
require(__DIR__ . '/fuego/init.php');
use OpenFuego\app\Getter as Getter;
add_action('genesis_entry_content', 'show_fuego');
function show_fuego() {

	$fuego = new Getter();
	$items = $fuego->getItems(20, 24, FALSE, TRUE); // quantity, hours, scoring, metadata
	// d($items);
	$html = '<script src="http://localhost/thenews/wp-content/themes/genesis-sample/jquery.masonry.min.js" type="text/javascript"></script>';
	$html .= '<script type="text/javascript">
		jQuery(document).ready(function($){
					$(".fuego-itembox-container").masonry({
						itemSelector : ".fuego-itembox",
						columnWidth : 310,
						gutterWidth: 30,
						isAnimated: true,
						animationOptions: {
							duration: 750,
							easing: "linear",
							queue: false
						}
					}).masonry("reload");
				});
		</script>';
	$html .= '<div class="fuego-itembox-container masonry">';
	
	foreach($items as $item) {
		// d($item);
		$html .= '<a href="'.$item['url'].'">
			<div id="link_'.$item['link_id'].'" class="fuego-itembox masonry-brick rank-'.$item['rank'].'">
				<div class="fuego-itembox-image" style="width: 310px; height: '.(310/$item['metadata']['thumbnail_width']) * $item['metadata']['thumbnail_height'].'px; background-size: 100% 100%; background-image: url('.$item['metadata']['thumbnail_url'].');">
					<div class="fuego-itembox-rankbox">'.$item['rank'].'</div>
				</div>
				<div class="fuego-itembox-headlinebox">
					<div class="fuego-itembox-provider-wrapper">
						<span class="fuego-itembox-provider">'.$item['metadata']['provider_name'].'</span>
					</div>
					<div class="fuego-itembox-headline">'.$item['metadata']['title'].'</div>
				</div>
				<div class="fuego-itembox-tweet">
					<div>
						<img width="40" height="40" alt="'.$item['tw_screen_name'].'\'s profile photo" src="'.$item['tw_profile_image_url_bigger'].'" class="fuego-itembox-tweet-image">
					</div>
				</div>
				<div class="fuego-itembox-tweet-text">
					<span class="fuego-item-handle">@'.$item['tw_screen_name'].'</span>: '.$item['tw_text'].'
				</div>
				<div style="clear:both;"></div>
			</div>
		</a>';
	}
	$html .= '</div>';
	echo $html;
}

genesis();
